swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/x-www-form-urlencoded
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: 
  restaurantProxy.key: &apigeeProxyKey CONFIGURED
  restaurantProxy.uri: &apigeeProxyUri CONFIGURED
x-a127-services: 
  cache:
    provider: volos-cache-memory
    options:
      name: cache
      ttl: 10000
  quota:
    provider: volos-quota-memory
    options:
      timeUnit: hour
      interval: 1
      allow: 2
  spikearrest:
    provider: "volos-spikearrest-memory"
    options:
      timeUnit: "minute"
      allow: 30
  oauth2:
    provider: volos-oauth-apigee
    options:
      key: *apigeeProxyKey
      uri: *apigeeProxyUri
      validGrantTypes:
        - client_credentials
        - authorization_code
        - implicit_grant
        - password
      tokenLifetime: 30000
      tokenPaths:
        authorize: /authorize
        token: /accesstoken
        invalidate: /invalidate
        refresh: /refresh
  analytics:
    provider: volos-analytics-apigee
    options:
      key: *apigeeProxyKey
      uri: *apigeeProxyUri
      proxy: remoteEatsProxy
      bufferSize: 1000
      flushInterval: 2000
      batchSize: 100
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    x-a127-apply: {}
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /restaurants:
    # binds a127 app logic to a route
    x-swagger-router-controller: restaurants
    x-a127-apply: 
      cache: {}
      quota: {}
      analytics: {}
      spikearrest: {}
    get:
      description: Returns a list of restaurants
      # used as the method name of the controller
      operationId: getRestaurants
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /restaurants/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: restaurants
    x-a127-apply: {}
    get:
      description: Returns a restaurant by its restID
      # used as the method name of the controller
      operationId: getRestaurantById
      parameters:
        - name: id
          in: path
          description: The restID of the restaurant
          required: true
          type: number
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /reviews:
    # binds a127 app logic to a route
    x-swagger-router-controller: reviews
    x-a127-apply: {}
    get:
      description: Returns a list of reviews
      # used as the method name of the controller
      operationId: getReviews
      parameters:
        - name: id
          in: query
          description: The restID of the restaurant to retrieve reviews for
          required: true
          type: number
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Returns a list of reviews
      # used as the method name of the controller
      operationId: postReview
      parameters:
        - name: review
          in: body
          description: The review to be posted
          required: true
          schema: 
            $ref: "#/definitions/Review"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Review:
    properties:
      restID:
        type: integer
      rating:
        type: integer
      review:
        type: string
    required: [restID, rating]
securityDefinitions:
  oauth2:
    type: oauth2
    flow: application
    tokenUrl: ignored